### ISSUE TITLE
Crashes the browser on MacOS when the serial port is overloaded

### ISSUE THREAD

**Issue by gunnbr** [derkyjadex/M8WebDisplay#5]
Using Chrome on MacOS, do something that sends a lot of data, like editing a sample waveform and scrolling it around. This often crashes the browser quite quickly.

**Comment by gunnbr** [comment]
Sorry, I thought I had a fix for this by just increasing the serial buffer, but it turns out the serial port is WAY overloaded when scrolling through a sample waveform. I'm looking for other fixes...

**Comment by derkyjadex** [comment]
I just managed to get a crash within seconds trying this myself. I was running a slightly old firmware version and I've just updated to the current 2.0.4 version. I can't seem to make it happen again now. Do you know a reliable way to cause the crash? Is it just the sample editing screen or have you come across this elsewhere?

This does seem like a bug in Chrome for the entire browser to crash but I'm wondering why it should struggle with the data rate. I don't think it's _that_ high.

**Comment by derkyjadex** [comment]
I've just pushed some changes which might help with this. The "Bad JPAD frame" messages should be gone now and I've increased the serial buffer size from 512 to 4096.

I've been catching up with the info on Discord and it looks like that buffer is the cause of the crashing so I hoping this will help.

**Comment by gunnbr** [comment]
Yeah, Tim said that increasing the serial buffer fixed the problem, but that didn't fix the problem for me. I should have documented which version of firmware I was testing with before, but now with 2.0.4, I haven't been able to reproduce the problem.

I also have my own C# version of the M8 display and it also didn't work with the sample editor before because the serial port was so overloaded, but that works great now too.

I think the changes that really helped fix this problem are:
* Fix: Sample editor - Zoomed selection movements was inaccurate and had visual artifacts
* Improved: Remote display - only send button presses when they are changed

I know the JPAD messages were coming in 60 times per second and I also noticed lots of drawing artifacts while scrolling in the sample editor before and now both of those are gone. I suspect both of those contributed to somehow overloading the serial port enough to crash the browser.

I need to do one more test using the same 2012 MacBook Air running Chrome where I had the problem originally. If it works there without crashing, I'll mark this as closed.

Thank you for the update!

**Comment by gunnbr** [comment]
I was unable to reproduce the crash on my old MacBook Air, so I think a combination of M8 firmware changes and the bigger serial buffer have solved the problem.

With the old MBA, I was able to get some artifacting on the sample editing screen, which I think is an indication that some data was lost, and I even got the M8 web display to stop updating a couple of times. Interestingly, the M8 was still responding to keypresses from the web display, so I could continue changing the start point of the current sample and hear the difference by playing it. I could also transition back to the song screen and start it playing. But this was all done blind since the display wasn't updating.

But, this bug is about the browser crashing and I'm no longer able to reproduce that, so I'll close this.
